language: go

addons:
    artifacts:
        debug: true
        paths:
        - $GOPATH/bin

dist: trusty

go:
    - 1.11

script:
    - go build
    - find . -type f -name honeyvent

deploy:
    provider: releases
    file: $GOPATH/bin/honeyvent
    skip_cleanup: true
    on:
      tags: true
