language: go

addons:
    artifacts:
        debug: true
        paths:
        - $GOPATH/bin

dist: trusty

go:
    - 1.11

script: go test github.com/honeycombio/honeyvent/...

after_success:
    - rm $GOPATH/bin/honeyvent
    - go install -ldflags "-X main.BuildID=1.${TRAVIS_BUILD_NUMBER}" github.com/honeycombio/honeyvent/...

deploy:
    provider: releases
    file: $GOPATH/bin/honeyvent
    skip_cleanup: true
    on:
      tags: true
