language: go

dist: trusty

go:
    - 1.11

script:
    - go build

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: ./honeyvent
    skip_cleanup: true
    on:
      tags: true
